# Generated by Django 3.2.11 on 2022-01-30 04:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 30, 4, 53, 4, 610710, tzinfo=utc)),
        ),
    ]
